version: '3'

services:
  pgadapter:
    image: gcr.io/cloud-spanner-pg-adapter/pgadapter
    env_file:
    - .env
    ports:
    - "5432:5432"
    volumes:
    - $HOME/.config/gcloud/application_default_credentials.json:/credentials.json:ro
    command: [ "/bin/bash", "/home/pgadapter/startup.sh", "-p", "${SPANNER_PROJECT}", "-i", "${SPANNER_INSTANCE}", "-d", "${SPANNER_DATABASE}", "-c", "/credentials.json", "-x" ]
  cloudsql-app:
    build:
      context: .
    image: cloudsql
    env_file:
    - .env
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
    volumes:
    - $HOME/.config/gcloud/application_default_credentials.json:/credentials.json:ro
    command: [ "java", "-jar", "app.jar", "cloudsql" ]
  spanner-app:
    build:
      context: .
    image: spanner
    depends_on:
    - pgadapter
    env_file:
    - .env
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
    - PGADAPTER_HOST=pgadapter
    - PGADAPTER_PORT=5432
    volumes:
    - $HOME/.config/gcloud/application_default_credentials.json:/credentials.json:ro
    command: [ "java", "-jar", "app.jar", "spanner" ]
